format_version: 10
pipelines:
  Second-pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-a66497e:
        git: https://github.com/vishnuvardhanmaari/cicd-magento.git
        username: vishnuvardhanmaari
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:m1F/NyeNYIh9IT+UVqUKEg==:Jz5HZWo5MgRbW/+cT+zPUv49wjSqYQfXAaJKtCRfjL0dXcHo5qKENOjPZi+PE6Wr
    stages:
    - first-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Firstjob:
            timeout: 0
            environment_variables:
              vishnu: vardhan
            tasks:
            - exec:
                arguments:
                  - -c
                  - |
                    pwd && ls
                    docker images
                command: /bin/bash
                run_if: passed 
           
